eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${eureka.instance.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 4
logging:
  config: classpath:logback.xml
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true
    defaultStatementTimeout: 30
  type-aliases-package: cn.yunyichina.log.common.entity.do_
kafka:
  consumer:
    bootstrapServers: 192.168.1.159:9000,192.168.1.159:9002,192.168.1.159:9002
    groupId: group-trace
    topicList:
      - topic-trace